<a href="https://colab.research.google.com/github/manjushree7/AI-ML/blob/main/2331414_ManjushreeTamang_Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Getting started with python

In [2]:
# Question 1
def length(value, unit):
  """
  This function converts length between meters and feet
  value: It stores numerical value to convert
  unit: It adds unit of the given value
  """
  if unit == 'm':
    return value * 3.28084   # meters to feet
  elif unit == 'f':
    return value / 3.28084   # feet to meters
  else:
    raise ValueError("Invalid unit. Use 'm' for meters or 'f' for feet.")

def weight(value, unit):
  """
  This function converts weight between kilograms and pounds
  value: It stores numerical value to convert
  unit: It adds unit of the given value
  """
  if unit == 'kg':
    return value * 2.20462   # kilograms to pounds
  elif unit == 'lb':
    return value / 2.20462   # pounds to kilograms
  else:
    raise ValueError("Invalid unit. Use 'kg' for kilograms or 'lb' for pounds.")

def volume(value, unit):
  """
  This function converts volume between liters and gallons
  value: It stores numerical value to convert
  unit: It adds unit of the given value
  """
  if unit == 'l':
    return value * 0.264172   # liters to gallons
  if unit == 'gal':
    return value / 0.264172   # gallons to liters
  else:
    raise ValueError("Invalid unit. Use 'l' for liters or 'gal' for gallons.")

def main():
  convert = {
      "1": (length, "m", "f", "meters", "feet"),
      "2": (weight, "kg", "lb", "kilograms", "pounds"),
      "3": (volume, "l", "gal", "liters", "gallons"),
  }
  print("Unit Converter")
  print("Select conversion type:")
  print("1: Length (meters to feet / feet to meters)")
  print("2: Weight (kilograms to pounds / pounds to kilograms)")
  print("3: Volume (liters to gallons / gallons to liters)")

  choice = input("Enter choice (1-3): ")
  if choice not in convert:
      print("Invalid choice. Please select a valid option.")
      return

  convert_func, unit1, unit2, unit1_name, unit2_name = convert[choice]

  print(f"Select direction:")
  print(f"1: {unit1_name} to {unit2_name}")
  print(f"2: {unit2_name} to {unit1_name}")

  direction = input("Enter choice (1-2): ")

  try:
    value = float(input(f"Enter value in {unit1_name if direction == '1' else unit2_name}: "))
  except ValueError:
    print("Invalid input. Please enter a numeric value.")
    return

  if direction == "1":
    result = convert_func(value, unit1)
    print(f"{value} {unit1_name} is {result:.2f} {unit2_name}.")
  elif direction == "2":
    result = convert_func(value, unit2)
    print(f"{value} {unit2_name} is {result:.2f} {unit1_name}.")
  else:
    print("Invalid choice. Please select a valid direction.")

if __name__ == "__main__":
    main()



Unit Converter
Select conversion type:
1: Length (meters to feet / feet to meters)
2: Weight (kilograms to pounds / pounds to kilograms)
3: Volume (liters to gallons / gallons to liters)
Enter choice (1-3): 1
Select direction:
1: meters to feet
2: feet to meters
Enter choice (1-2): 2
Enter value in feet: 5.5
5.5 feet is 1.68 meters.


In [3]:
# Question 2
def calculate_sum(num):
    """Returns the sum of a list of numbers"""
    return sum(num)

def calculate_average(num):
    """Returns the average of a list of numbers"""
    return sum(num) / len(num) if num else 0

def find_maximum(num):
    """Returns the maximum value in a list of numbers"""
    return max(num)

def find_minimum(num):
    """Returns the minimum value in a list of numbers"""
    return min(num)

def main():
    """Main function to handle user input and perform calculations"""
    operations = {
        "1": (calculate_sum, "Sum"),
        "2": (calculate_average, "Average"),
        "3": (find_maximum, "Maximum"),
        "4": (find_minimum, "Minimum"),
    }

    print("Mathematical Operations on a List of Numbers")
    print("Select an operation:")
    print("1: Find the Sum")
    print("2: Find the Average")
    print("3: Find the Maximum")
    print("4: Find the Minimum")

    choice = input("Enter choice (1-4): ")

    if choice not in operations:
        print("Invalid choice. Please select a valid option")
        return

    try:
        num = list(map(float, input("Enter a list of numbers separated by spaces: ").split()))
        if not num:
            raise ValueError("The list cannot be empty.")
    except ValueError:
        print("Invalid input. Please enter numeric values separated by spaces.")
        return

    operation_func, operation_name = operations[choice]
    result = operation_func(num)
    print(f"The {operation_name} of the given numbers is: {result:.2f}")

if __name__ == "__main__":
    main()

Mathematical Operations on a List of Numbers
Select an operation:
1: Find the Sum
2: Find the Average
3: Find the Maximum
4: Find the Minimum
Enter choice (1-4): 1
Enter a list of numbers separated by spaces: 12
The Sum of the given numbers is: 12.00


In [4]:
# Question 3
def extract_every_other(lst):
    return lst[::2]
print(extract_every_other([1, 2, 3, 4, 5, 6]))

[1, 3, 5]


In [5]:
# Question 4
def get_sublist(lst, start, end):
    return lst[start:end+1]
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

[3, 4, 5]


In [6]:
# Question 5
def reverse_list(lst):
    return lst[::-1]
print(reverse_list([1, 2, 3, 4, 5]))


[5, 4, 3, 2, 1]


In [7]:
# Question 6
def remove_first_last(lst):
    return lst[1:-1]
print(remove_first_last([1, 2, 3, 4, 5]))


[2, 3, 4]


In [8]:
# Question 7
def get_first_n(lst, n):
    return lst[:n]
print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]


In [9]:
# Question 8
def get_last_n(lst, n):
    return lst[-n:]
print(get_last_n([1, 2, 3, 4, 5], 2))

[4, 5]


In [10]:
# Question 9
def reverse_skip(lst):
    return lst[-2::-2]
print(reverse_skip([1, 2, 3, 4, 5, 6]))

[5, 3, 1]


In [11]:
# Question 10
def flatten(lst):
    return [item for sublist in lst for item in sublist]
print(flatten([[1, 2], [3, 4], [5]]))

[1, 2, 3, 4, 5]


In [12]:
# Question 11
def access_nested_element(lst, indices):
    element = lst  #start from the outermost list
    for index in indices:
        element = element[index]  #navigate to the next level
    return element
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
print(access_nested_element(nested_list, indices))

6


In [13]:
# Question 12
def sum_nested(lst):
    total = 0
    for element in lst:
        if isinstance(element, list):  #check if the element is a list
            total += sum_nested(element)  #recursively sum elements in sublist
        else:
            total += element  # Add the number to the total
    return total
nested_list = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nested_list))

21


In [14]:
# Question 13
def remove_element(lst, elem):
    for i in range(len(lst)):
        if isinstance(lst[i], list):  #check if the element is a sublist
            lst[i] = remove_element(lst[i], elem)  #recursively remove from sublist
            while elem in lst[i]:  #remove all occurrences of elem in the current sublist
                lst[i].remove(elem)
        elif isinstance(lst[i], list) == False and lst[i] == elem:  #handle integer elements
            lst.remove(lst[i])  #remove integer element if it matches elem
    return lst
nested_list = [[1, 2], [3, 2], [4, 5]]
elem = 2
print(remove_element(nested_list, elem))

[[1], [3], [4, 5]]


In [15]:
# Question 14
def find_max(lst):
    max_element = None  #initialize as None to handle the first comparison
    for element in lst:
        if isinstance(element, list):  #if the element is a sublist, call recursively
            element_max = find_max(element)
            if element_max is not None:  #only compare if the sublist is not empty
                if max_element is None or element_max > max_element:
                    max_element = element_max
        else:
            if max_element is None or element > max_element:
                max_element = element  #update max_element if a larger element is found

    return max_element
nested_list = [[1, 2], [3, [4, 5]], 6]
print(find_max(nested_list))

6


In [16]:
# Question 15
def count_occurrences(lst, elem):
    count = 0  #initialize the count to zero
    for element in lst:
        if isinstance(element, list):
            count += count_occurrences(element, elem)  #add count from the sublist
        else:
            if element == elem:  #if the element matches the target element, increase the count
                count += 1
    return count
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
print(count_occurrences(lst, elem))

3


In [17]:
# Question 16
def deep_flatten(lst):
    flattened = []  #initialize an empty list to hold the flattened elements
    for element in lst:
        if isinstance(element, list):
            flattened.extend(deep_flatten(element))  # Flatten the sublist and add its elements
        else:
            flattened.append(element)  # If it's not a list, add the element to the flattened list
    return flattened
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(nested_list))

[1, 2, 3, 4, 5, 6, 7, 8]


In [18]:
# Question 17
def average_nested(lst):
    total_sum = 0
    total_count = 0

    for element in lst:
        if isinstance(element, list):
            sub_sum, sub_count = average_nested(element)
            total_sum += sub_sum  #add the sum from the sublist
            total_count += sub_count  #add the count from the sublist
        else:
            total_sum += element  #add the current element to the sum
            total_count += 1  #increase the count of elements

    #return the sum and count of elements to calculate average later
    return total_sum, total_count

#wrapper to calculate the average based on the sum and count
def calculate_average(lst):
    total_sum, total_count = average_nested(lst)
    return total_sum / total_count

nested_list = [[1, 2], [3, 4], [5, 6]]
print(calculate_average(nested_list))

3.5


## Getting started with Numpy

In [19]:
import numpy as np

In [20]:
# Question 1
#initialize a 2x2 empty array (list) with None or zeros
empty_array = [[None, None], [None, None]]
print(empty_array)

[[None, None], [None, None]]


In [21]:
# Question 2
#initialize a 4x2 array with all elements set to 1
ones_array = np.ones((4, 2), dtype=int)
print(ones_array)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [22]:
# Question 3
#define the shape and fill value
shape = (4, 2)
fill_value = 7
#create a 4x2 array filled with the value 7
filled_array = np.full(shape, fill_value, dtype=int)
print(filled_array)

[[7 7]
 [7 7]
 [7 7]
 [7 7]]


In [23]:
# Question 4
original_array = np.array([[1, 2], [3, 4]])
zeros_array = np.zeros_like(original_array)
print(zeros_array)

[[0 0]
 [0 0]]


In [24]:
# Question 5
original_array = np.array([[1, 2], [3, 4]])
ones_array = np.ones_like(original_array)
print(ones_array)

[[1 1]
 [1 1]]


In [25]:
# Question 6
new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print(np_array)

[1 2 3 4]


In [26]:
# Question 7
array = np.arange(10, 50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [27]:
# Question 8
array = np.arange(9)
#reshape the array into a 3x3 matrix
matrix = array.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
# Question 9
#create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
# Question 10
#create a random array of size 30
random_array = np.random.random(30)

#calculate the mean of the array
mean_value = random_array.mean()

print("Random Array:", random_array)
print("Mean of the array:", mean_value)

Random Array: [0.91990243 0.0297249  0.61475234 0.81707976 0.36725869 0.55974605
 0.70519935 0.27810747 0.21083758 0.23052389 0.77476086 0.66339061
 0.55591126 0.808332   0.40018278 0.74767262 0.25349776 0.93490837
 0.90617168 0.03635577 0.06260503 0.1961559  0.7122324  0.66054196
 0.74672343 0.26492037 0.81953736 0.9861889  0.95376977 0.08084396]
Mean of the array: 0.5432611740721338


In [30]:
# Question 11
#create a 10x10 array with random values
random_array = np.random.random((10, 10))

#find the minimum value in the array
min_value = random_array.min()

#find the maximum value in the array
max_value = random_array.max()

print("Random Array:")
print(random_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Random Array:
[[0.51297961 0.98690842 0.39758753 0.21126864 0.80581129 0.71495257
  0.27482145 0.71302763 0.66677381 0.09427902]
 [0.20242876 0.82518354 0.52081344 0.92121816 0.81661316 0.63610965
  0.61502682 0.48231947 0.06761475 0.64088177]
 [0.23537852 0.59660411 0.57438932 0.22503301 0.01637803 0.44706941
  0.09955709 0.27399885 0.99805512 0.01077578]
 [0.51605561 0.64826614 0.4945697  0.17056205 0.33816369 0.79761141
  0.64674796 0.40085101 0.92380193 0.62857989]
 [0.08229351 0.0606239  0.14102676 0.2035521  0.0882245  0.74055552
  0.41723214 0.03096019 0.17553103 0.50935188]
 [0.4467432  0.88302669 0.98057678 0.04848782 0.77786171 0.62877109
  0.76632126 0.88183044 0.86456972 0.95676838]
 [0.10517827 0.74185922 0.48738037 0.36459564 0.04675839 0.55066534
  0.71895762 0.09469654 0.08949458 0.67097616]
 [0.49293067 0.85302725 0.31810674 0.5544793  0.2615563  0.68867458
  0.32447452 0.67559317 0.13559029 0.68261134]
 [0.08600899 0.51830756 0.21039452 0.46026918 0.68529797 0.7747147

In [31]:
# Question 12
#create a zero array of size 10
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [32]:
# Question 13
arr = [1, 2, 0, 0, 4, 0]
#reverse the array
reversed_arr = arr[::-1]
print(reversed_arr)

[0, 4, 0, 0, 2, 1]


In [33]:
# Question 14
# Create 2D array of ones with shape (5, 5)
array = np.ones((5, 5))
# Set the inner elements to 0
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [34]:
# Question 15
#create 8x8 array of zeros
matrix = np.zeros((8, 8))
#fill the checkerboard pattern
matrix[::2, ::2] = 1  #set 1 on every even row and even column
matrix[1::2, 1::2] = 1  #set 1 on every odd row and odd column
print(matrix)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [35]:
# Question 15
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [36]:
add = x + y
print("Addition of x and y:\n", add)

Addition of x and y:
 [[ 6  8]
 [10 13]]


In [37]:
subtract = x - y
print("Subtraction of x and y:\n", subtract)

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]


In [38]:
multiply_x = x * 2
multiply_y = y * 2
print("Multiplication of x by 2:\n", multiply_x)
print("Multiplication of y by 2:\n", multiply_y)

Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]
Multiplication of y by 2:
 [[10 12]
 [14 16]]


In [39]:
square_x = np.square(x)
square_y = np.square(y)
print("Square of each element of x:\n", square_x)
print("Square of each element of y:\n", square_y)

Square of each element of x:
 [[ 1  4]
 [ 9 25]]
Square of each element of y:
 [[25 36]
 [49 64]]


In [40]:
dot_vw = np.dot(v, w)
print("Dot product between v and w:", dot_vw)

Dot product between v and w: 219


In [41]:
dot_xv = np.dot(x, v)
print("Dot product between x and v:\n", dot_xv)

Dot product between x and v:
 [29 77]


In [42]:
dot_xy = np.dot(x, y)
print("Dot product between x and y:\n", dot_xy)

Dot product between x and y:
 [[19 22]
 [50 58]]


In [43]:
concat_xy = np.concatenate((x, y), axis=1)
print("Concatenate x and y along rows:\n", concat_xy)

Concatenate x and y along rows:
 [[1 2 5 6]
 [3 5 7 8]]


In [44]:
v_w_reshaped = np.vstack((v, w))  # To make both v and w 2D for vertical stacking
print("Concatenate v and w along columns:\n", v_w_reshaped)

Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]


In [45]:
try:
    concat_xv = np.concatenate((x, v), axis=1)  # This will fail because x is 2D and v is 1D
    print("Concatenate x and v:\n", concat_xv)
except ValueError as e:
    print(f"Error: {e}")

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [48]:
# Define matrix A
A = np.array([[3, 4], [7, 8]])

# Compute inverse of A
A_inv = np.linalg.inv(A)

# Compute A * A_inv
I = np.dot(A, A_inv)

# Print results
print("A:\n", A)
print("A_inv:\n", A_inv)
print("A * A_inv:\n", I)

# Check if A * A_inv is close to identity matrix
print("Is A * A_inv close to identity matrix?", np.allclose(I, np.eye(2)))

A:
 [[3 4]
 [7 8]]
A_inv:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is A * A_inv close to identity matrix? True


In [49]:
# Define the coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Define the constant matrix B
B = np.array([-1, -3, 9])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)

# Print the result
print("Solution for x, y, z:", X)

Solution for x, y, z: [ 2.  1. -2.]


In [50]:
# Define the coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Define the constant matrix B
B = np.array([-1, -3, 9])

# Solve for X using A⁻¹ * B
X = np.linalg.inv(A) @ B  # Alternative: np.dot(np.linalg.inv(A), B)

# Print the result
print("Solution for x, y, z:", X)

Solution for x, y, z: [ 2.  1. -2.]


## How fast is numpy and python


In [54]:
#Question 1
#Python
import time
import random
#generate two large lists of size 1,000,000 with random integers
size = 1_000_000
list1 = [random.randint(1, 100) for _ in range(size)]
list2 = [random.randint(1, 100) for _ in range(size)]

#measure the time for element-wise addition
start_time = time.time()
result = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()

#print the time taken
print(f"Time taken for element-wise addition using Python lists: {end_time - start_time:.5f} seconds")

Time taken for element-wise addition using Python lists: 0.05743 seconds


In [52]:
#Numpy
# Generate two large NumPy arrays of size 1,000,000 with random integers
array1 = np.random.randint(1, 101, size)
array2 = np.random.randint(1, 101, size)

# Measure the time for element-wise addition using NumPy arrays
start_time = time.time()
result_array = array1 + array2  # NumPy's vectorized addition
end_time = time.time()

# Print the time taken
print(f"Time taken for element-wise addition using NumPy: {end_time - start_time:.5f} seconds")


Time taken for element-wise addition using NumPy: 0.01081 seconds


In [ ]:
# Question 2
#Python
# Generate two large lists of size 1,000,000 with random integers
size = 1_000_000
list1 = [random.randint(1, 100) for _ in range(size)]
list2 = [random.randint(1, 100) for _ in range(size)]

# Measure the time for element-wise multiplication using lists
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()

# Print the time taken
print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time:.5f} seconds")


In [56]:
#Numpy
# Generate two large NumPy arrays of size 1,000,000 with random integers
array1 = np.random.randint(1, 101, size)
array2 = np.random.randint(1, 101, size)

# Measure the time for element-wise multiplication using NumPy arrays
start_time = time.time()
result_array = array1 * array2  # NumPy's vectorized multiplication
end_time = time.time()

# Print the time taken
print(f"Time taken for element-wise multiplication using NumPy: {end_time - start_time:.5f} seconds")

Time taken for element-wise multiplication using NumPy: 0.00462 seconds


In [57]:
# Question 3
#Python
# Generate two large lists of size 1,000,000 with random integers
size = 1_000_000
list1 = [random.randint(1, 100) for _ in range(size)]
list2 = [random.randint(1, 100) for _ in range(size)]

# Measure the time for dot product using lists
start_time = time.time()
dot_product = sum(list1[i] * list2[i] for i in range(size))  # Manual dot product calculation
end_time = time.time()

# Print the time taken
print(f"Time taken for dot product using Python lists: {end_time - start_time:.5f} seconds")
print(f"Dot Product (Python List): {dot_product}")


Time taken for dot product using Python lists: 0.08269 seconds
Dot Product (Python List): 2549860040


In [58]:
# Numpy
# Generate two large NumPy arrays of size 1,000,000 with random integers
array1 = np.random.randint(1, 101, size)
array2 = np.random.randint(1, 101, size)

# Measure the time for dot product using NumPy arrays
start_time = time.time()
dot_product_np = np.dot(array1, array2)  # NumPy's optimized dot product function
end_time = time.time()

# Print the time taken
print(f"Time taken for dot product using NumPy: {end_time - start_time:.5f} seconds")
print(f"Dot Product (NumPy): {dot_product_np}")

Time taken for dot product using NumPy: 0.00242 seconds
Dot Product (NumPy): 2550335984


In [60]:
# Question 4
size = 100  # Reduce the size for testing
matrix1 = [[random.randint(1, 100) for _ in range(size)] for _ in range(size)]
matrix2 = [[random.randint(1, 100) for _ in range(size)] for _ in range(size)]

start_time = time.time()
result = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
end_time = time.time()

print(f"Time taken for 100x100 matrix multiplication using Python lists: {end_time - start_time:.5f} seconds")

Time taken for 100x100 matrix multiplication using Python lists: 0.21634 seconds


In [61]:
# Generate two 1000x1000 NumPy arrays with random integers
matrix1_np = np.random.randint(1, 101, (size, size))
matrix2_np = np.random.randint(1, 101, (size, size))

# Measure the time for matrix multiplication using NumPy
start_time = time.time()
result_np = np.dot(matrix1_np, matrix2_np)  # Optimized matrix multiplication
end_time = time.time()

# Print the time taken
print(f"Time taken for matrix multiplication using NumPy: {end_time - start_time:.5f} seconds")

Time taken for matrix multiplication using NumPy: 0.00111 seconds
